MANAGERS = 1
WORKERS = 1

ANSIBLE_GROUPS = {
  "managers" => ["manager[1:#{MANAGERS}]"],
  "workers" => ["worker[1:#{WORKERS}]"],
  "all_groups:children" =>  [
    "managers", "workers"
  ]
}

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  # config.vm.box_url = "https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  (1..MANAGERS).each do |manager_id|
    config.vm.define "manager#{manager_id}" do |manager|
      manager.vm.hostname = "manager#{manager_id}"
      manager.vm.network "private_network", ip: "192.168.77.#{20 + manager_id}"
      manager.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
    end
  end

  (1..WORKERS).each do |worker_id|
    config.vm.define "worker#{worker_id}" do |worker|
      worker.vm.hostname = "worker#{worker_id}"
      worker.vm.network "private_network", ip: "192.168.77.#{30 + worker_id}"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
    end
  end

  config.vm.provision "swarm", type: "ansible" do |ansible|
    ansible.limit = "all_groups"
    ansible.playbook = "ansible-swarm.yml"
    ansible.groups = ANSIBLE_GROUPS
    ansible.verbose = "vv"
  end
end
